name: Publish package to NPM
on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'The kind of version bump. One of: patch, minor, major'
        required: true
        default: 'patch'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Attach Head
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Set Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install and Build
        run: |
          yarn install
          yarn build
          git checkout yarn.lock

      - name: Set Bump
        shell: bash -ex {0}
        run: |
          if [ "${{ github.event.inputs.bump }}" = "major" ] ; then
            BUMP=major
            BUMP_EMOJI=🚀
          elif [ "${{ github.event.inputs.bump }}" = "minor" ] ; then
            BUMP=minor
            BUMP_EMOJI=📦
          else
            BUMP=patch
            BUMP_EMOJI=🔧
          fi
          echo "BUMP=${BUMP}" >> $GITHUB_ENV
          echo "BUMP_EMOJI=${BUMP_EMOJI}" >> $GITHUB_ENV

      - name: Bump package.json
        run: |
          yarn version --${BUMP} --message "$BUMP_EMOJI %s"

      - run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
